version: "3.7"
services:
  app:
    build:
      context: .
      args:
        - GIT_REPO=${GIT_REPO}
        - GIT_BRANCH=${GIT_BRANCH}
        - PROJECT_NAME=${PROJECT_NAME}
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - CONTAINER_NAME=${CONTAINER_NAME}
    container_name: ${CONTAINER_NAME}
    command: "pm2-runtime start dist/${PROJECT_NAME}/server/main.js /dev/null"
