version: "3.7"
services:
  app:
    build:
      context: .
      args:
        - GIT_REPO=${GIT_REPO}
        - GIT_BRANCH=${GIT_BRANCH}
        - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
        - PROJECT_NAME=${PROJECT_NAME}
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - CONTAINER_NAME=${CONTAINER_NAME}
    container_name: ${CONTAINER_NAME}
