version: "3.7"
services:
  app:
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_ID}-router.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${APP_ID}-router.entrypoints=web"
      - "traefik.http.middlewares.${APP_ID}-redirect-middleware.redirectscheme.scheme=https"
      - "traefik.http.routers.${APP_ID}-router.middleware=${APP_ID}-redirect-middleware"
      - "traefik.http.routers.${APP_ID}-secure-router.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${APP_ID}-secure-router.entrypoints=Host(`${HOST}`)"
      - "traefik.http.routers.${APP_ID}-secure-router.tls=true"
      - "traefik.http.routers.${APP_ID}-secure-router.tls.certresolver=lets-encrypt"
      - "traefik.http.services.${APP_ID}-service.loadbalancer.server.port=${PORT}"
      - "traefik.http.routers.${APP_ID}-secure-router.service=${APP_ID}-service"

networks:
  traefik:
    external: True
